# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1

workflows:
  json-resume:
    jobs:
      - build-resume

jobs:
  build-resume:
    working_directory: ~/project
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: "Fetch json resume cli"
          # https://github.com/jsonresume/resume-cli/issues/365
          command: "npm install resume-cli"
      - run:
          name: "Export JSON resume as PDF"
          command: "npx resume export resume.html"
      # persist resume.html as a build artifact
      - store_artifacts:
          path: ~/project
          destination: resume.html
