# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  # node: circleci/node@4.1
  aws-cli: circleci/aws-cli@3.1.1

workflows:
  json-resume:
    jobs:
      - build-resume

jobs:
  build-resume:
    working_directory: ~/project
    docker:
      - image: circleci/node:10.16.3
    environment:
      RESUME_TARGET: index.html
    steps:
      - checkout
      - run:
          name: "Fetch AWS CLI"
          command: |
            sudo apt-get update
            sudo apt-get install awscli
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - run:
          name: "Fetch json resume cli"
          # https://github.com/jsonresume/resume-cli/issues/365
          command: "npm install resumed jsonresume-theme-mocha-responsive"
      - run:
          name: "Generate resume"
          command: npx resumed render resume.json --output $RESUME_TARGET
      - run:
          name: Upload resume to S3
          command: aws s3 cp $RESUME_TARGET s3://www.christopherblackresume
